### ISSUE TITLE
Errors on local server

### ISSUE THREAD

**Issue by Hurricane86** [minical/minical#59]
Hi guys,

i would like to test this great project but i have issues trying to setup it locally with WAMP.
I have followed the installation instructions but when i run the _install.php_ script i get this error:

`​ GET http://localhost/auth/register 404 (Not Found)`

this without pointing the localhost the the public minical folder. Doing it I get these errors type:

```
A PHP Error was encountered

Severity: Warning

Message: scandir(application/extensions/,application/extensions/): Impossibile trovare il file specificato. (code: 2)

Filename: config/routes.php

Line Number: 51
```

and a lot of client side errors like this:

```
GEThttp://localhost/minical/public/css/bootstrap.min.css
[HTTP/1.1 404 Not Found 1ms]
```

any advice?

thanks
​

**Comment by pankaj9296** [comment]
Hi @Hurricane86, Thanks for reporting the issue.
We have pushed an update that will fix the above scenario.

Please pull the latest from the Master branch and visit http://localhost/minical/public/auth/register (Or http://localhost/path-to-public-folder/auth/register if the miniCal project is at a different location)

Thanks

**Comment by shuklaalok7** [comment]
@pankaj9296 I am still facing the same issue with the latest commit 73789d867d86ad9a0c093750afc7e97dd73b6e89 in the `master` branch. After completing the installation, `/auth/register` or `/auth/login` URLs give `404`.

![image](https://user-images.githubusercontent.com/1621571/131894060-4eba4eef-69fa-4d19-b783-f312ef8bedfa.png)

**Comment by pankaj9296** [comment]
@shuklaalok7 Looks like you are trying to access miniCal project in the wrong directory.
Are you sure miniCal project is located in apache's Document root?
The error is related to the apache server and not specific to miniCal configuration.

Please join our discord server for immediate support. 
https://discord.gg/dnnZQ4Ft
